version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/auth-server
    overwrite: yes
permissions:
  - object: /
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/run-server.sh
      timeout: 300
      runas: root